[build]
base = "docs"
publish = "public"
command = "make ci-production-build"

[build.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENVIRONMENT = "production"

[context.deploy-preview]
command = "make ci-preview-build"

[context.branch-deploy]
command = "make ci-preview-build"
