title = "Vector"
baseURL = "/"
disableKinds = ["taxonomy", "term"]
copyright = "Datadog, Inc."
languageCode = "en-us"

[build]
writeStats = true

[minify]
disableSVG = true

# Syntax highlighting
[markup.highlight]
noClasses = false

# Markup config overrides
[markup.goldmark.renderer]
unsafe = true

# Language configuration
defaultContentLanguage = "en"

[languages.en]
title = "Vector"
contentDir = "content/en"
weight = 1

[params]
description = "A lightweight, ultra-fast tool for building observability pipelines"
tagline = "Take control of your observability stack"
undertagline = "Collect, transform, and route all your observability data with one simple tool"
subtagline = "Vector is deployed over 1,000,000 times per month by Fortune 500 companies and startups"
alpine_js_version = "2.8.2"
ionicons_version = "5.4.0"
site_logo = "img/vector-open-graph.png"
favicon = "favicon.ico"

# Update this every time there's a new "generation" of the site. Incrementing this forces the browser to refresh any
# state persisted in localStorage. You should do that whenever there's some change in the front-end logic that requires
# wiping out the user's localStorage, for example a new news banner that we want to show. Think of it as cache
# invalidation that we control.
site_generation = 1

# Aesthetics
[[params.fonts]]
name = "Segoe UI"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Source Sans Pro"
sizes = [300, 400, 600, 700]
type = "secondary"

[[params.fonts]]
name = "Source Code Pro"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social]
twitter_handle = "vectordotdev"
github_repo = "timberio/vector"
discord = "https://chat.vector.dev"

## Menus

# Main page doc links
[[menu.doc_quick_links]]
name = "Quickstart"
url = "/docs/setup/quickstart"
params = { emphasis = true }
weight = 1

[[menu.doc_quick_links]]
name = "Vector Remap Language"
url = "/docs/reference/vrl"
weight = 2

[[menu.doc_quick_links]]
name = "Components"
url = "/components"
weight = 3

# Navbar menu
[[menu.navbar]]
name = "Docs"
url = "/docs"
params = { flyout = true }
weight = 1

[[menu.navbar]]
name = "Guides"
url = "/guides"
weight = 2

[[menu.navbar]]
name = "Components"
url = "/components"
weight = 3

[[menu.navbar]]
name = "Download"
url = "/download"
weight = 4

[[menu.navbar]]
name = "Blog"
url = "/blog"
weight = 5

# Footer menu
[[menu.footer]]
name = "About"
identifier = "about"
weight = 1

[[menu.footer]]
name = "What is Vector?"
url = "/docs/about"
parent = "about"
weight = 1

[[menu.footer]]
name = "Contact us"
url = "/community"
parent = "about"
weight = 2

[[menu.footer]]
name = "Components"
identifier = "components"
weight = 2

[[menu.footer]]
name = "Sources"
url = "/docs/reference/configuration/sources"
parent = "components"
weight = 1

[[menu.footer]]
name = "Transforms"
url = "/docs/reference/configuration/transforms"
parent = "components"
weight = 2

[[menu.footer]]
name = "Sinks"
url = "/docs/reference/configuration/sinks"
parent = "components"
weight = 3

[[menu.footer]]
name = "Setup"
identifier = "setup"
weight = 3

[[menu.footer]]
name = "Installation"
url = "/docs/setup/installation"
parent = "setup"
weight = 1

[[menu.footer]]
name = "Deployment"
url = "/docs/setup/deployment"
parent = "setup"
weight = 2

[[menu.footer]]
name = "Configuration"
url = "/docs/reference/configuration"
parent = "setup"
weight = 3

[[menu.footer]]
name = "Administration"
url = "/docs/administration"
parent = "setup"
weight = 4

[[menu.footer]]
name = "Community"
identifier = "community"
weight = 4

[[menu.footer]]
name = "GitHub"
url = "https://github.com/timberio/vector"
parent = "community"
weight = 1

[[menu.footer]]
name = "Twitter"
url = "https://twitter.com/vectordotdev"
parent = "community"
weight = 2

[[menu.footer]]
name = "Chat"
url = "https://chat.vector.dev"
parent = "community"
weight = 3

# Extra links under the "Meta" section in the docs
[[menu.meta]]
name = "Privacy"
url = "https://github.com/timberio/vector/blob/master/PRIVACY.md"
weight = 1

[[menu.meta]]
name = "Release"
url = "https://github.com/timberio/vector/blob/master/RELEASING.md"
weight = 2

[[menu.meta]]
name = "Security"
url = "https://github.com/timberio/vector/security/policy"
weight = 3

# Buttons in "community" section on main page
[[menu.community]]
name = "View GitHub repo"
params = { color = "black", dark = "white", icon = "github" }
url = "https://github.com/timberio/vector"
weight = 1

[[menu.community]]
name = "Chat with us on Discord"
params = { color = "discord-purple", icon = "discord" }
url = "https://chat.vector.dev"
weight = 2


# Mini icons in navbar and footer
[[menu.comms]]
name = "Twitter"
params = { color = "twitter-blue", icon = "twitter" }
url = "https://twitter.com/vectordotdev"
weight = 1

[[menu.comms]]
name = "GitHub"
params = { color = "black", dark = "white", icon = "github" }
url = "https://github.com/timberio/vector"
weight = 2

[[menu.comms]]
name = "Chat"
params = { color = "discord-purple", icon = "discord" }
url = "https://chat.vector.dev"
weight = 3

[[menu.comms]]
name = "RSS"
params = { color = "rss-orange", icon = "rss" }
url = "/blog/index.xml"
weight = 4

# Links in subfooter
[[menu.subfooter]]
name = "Security policy"
url = "https://github.com/timberio/vector/blob/master/PRIVACY.md"
weight = 1

[[menu.subfooter]]
name = "Privacy policy"
url = "https://github.com/timberio/vector/blob/master/PRIVACY.md"
weight = 2

[[menu.flyout]]
name = "Documentation"
identifier = "docs"
url = "/docs"
weight = 1

[[menu.flyout]]
name = "Quickstart"
parent = "docs"
url = "/docs/setup/quickstart"
weight = 1

[[menu.flyout]]
name = "Components"
identifier = "components"
url = "/components"
weight = 2

[[menu.flyout]]
name = "Sources"
parent = "components"
url = "/docs/reference/configuration/sources"
weight = 1

[[menu.flyout]]
name = "Transforms"
parent = "components"
url = "/docs/reference/configuration/transforms"
weight = 2

[[menu.flyout]]
name = "Sinks"
parent = "components"
url = "/docs/reference/configuration/sinks"
weight = 3

[[menu.flyout]]
name = "Vector Remap Language"
identifier = "vrl"
url = "/docs/reference/vrl"
weight = 3

[[menu.flyout]]
name = "Expressions"
parent = "vrl"
url = "/docs/reference/vrl/expressions"
weight = 1

[[menu.flyout]]
name = "Functions"
parent = "vrl"
url = "/docs/reference/vrl/functions"
weight = 2

[[menu.flyout]]
name = "Errors"
parent = "vrl"
url = "/docs/reference/vrl/errors"
weight = 3

[[menu.flyout]]
name = "Examples"
parent = "vrl"
url = "/docs/reference/vrl/examples"
weight = 4

[[menu.flyout]]
name = "Pages"
identifier = "pages"
weight = 4

[[menu.flyout]]
name = "Download"
parent = "pages"
url = "/download"
weight = 1

[[menu.flyout]]
name = "Releases"
parent = "pages"
url = "/releases"
weight = 2

[[menu.flyout]]
name = "Highlights"
parent = "pages"
url = "/highlights"
weight = 3
