# This Action triggers a build of Vector's Rustdoc each time a PR is merged
# to `master`.
#
# Netlify account for Rustdoc site: https://app.netlify.com/sites/vector-rustdoc
# Repo that builds the site: https://github.com/timberio/vector-rustdoc
# Root URL for Rustdoc site: https://vector-rustdoc.netlify.app
# Pretty URL for the published docs: https://rustdoc.vector.dev
name: Publish Vector Rustdoc

# Action is triggered only if changes are merged, not just pushed
on:
  push:
    branches:
      - master

jobs:
  trigger-site-build:
    name: Trigger a build of Vector's Rustdoc site (hosted by Netlify)
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger build via CURL request
        # Trigger a new build via webhook
        run: curl -X POST -d "{}" "${{ secrets.NETLIFY_RUSTDOC_HOOK }}"
